root: true
extends:
  - airbnb-base
  - google
  - plugin:jest/recommended
  - plugin:node/recommended
  - plugin:prettier/recommended
plugins:
  - jest
  - node
  - prettier
rules:
  max-len:
    - error
    - 110 # keep in sync with .prettierrc.yaml printWidth
    - 2
  require-jsdoc: off
  no-bitwise: off
  strict: off
  class-methods-use-this: off
  consistent-return: off
  quotes:
    - error
    - double
    - avoidEscape: true
overrides:
  - files:
      - "integration/**"
      - "**/__tests__/**"
      - "**/__mocks__/**"
    env:
      jest: true
    rules:
      # dev dependencies are hoisted to the root
      import/no-extraneous-dependencies: off
      # mocked modules are imported before helpers
      import/order: off
      node/no-extraneous-require: off
      node/no-unpublished-require: off
      node/no-unsupported-features/es-syntax:
        - error
        - ignores:
            - asyncFunctions
            # jest transpiles fast-async
      no-console: off
