export enum AssignmentOperator {
  BINARY_AND_EQUALS,
  BINARY_OR_EQUALS,
  BINARY_XOR_EQUALS,
  DIVISION_EQUALS,
  EQUALS,
  MINUS_EQUALS,
  MODULO_EQUALS,
  MULTIPLICATION_EQUALS,
  PLUS_EQUALS,
  SHIFT_LEFT_EQUALS,
  SHIFT_RIGHT_EQUALS,
  UNSIGNED_SHIFT_RIGHT_EQUALS,
}
