"use strict";

const fs = require("fs");
const _ = require("lodash");
const SweetscapeImporter = require("../lib/sweetscape/sweetscape-importer");

// const structureFolder = `${__dirname}/../__fixtures__/`;
const structureFolder = "/home/guillaume/dev/010-structures";

describe("Sweetscape Importer", () => {
  const importer = new SweetscapeImporter();
  _.each(
    [
      // "010",
      "010Theme",
      "7ZIP",
      "ADF",
      "AndroidManifest",
      "AndroidResource",
      "AndroidTrace",
      "AndroidVBMeta",
      "AVI",
      "BaseMedia",
      "Bash",
      "Batch",
      "BMP",
      "BPlist",
      "BSON",
      "CAB",
      "CAP",
      "CDA",
      "CLASSAdv",
      "CLASS",
      "CPP",
      "CRX",
      "Cryptfs",
      "CSharp",
      "CSS",
      "DBF",
      "DDS",
      "DEX",
      "DMP",
      "Drive",
      "EatonAPR48",
      "EDID",
      "ELF",
      "ElTorito",
      "EMF",
      "EOT",
      "EVSB",
      "EXE",
      "EZTap_EZVIEW2",
      "FLV",
      "FNT",
      "FTS",
      "GGPK",
      "GIF",
      "Goclever",
      "GZip",
      "HFSJournal",
      "HiewCMarkers",
      "HTML",
      "ICO",
      "IGI2_RES",
      "IGI2_SPR",
      "IGI2_TEX",
      "IGI2_THM",
      "IGI2_TLM",
      "IGI2_TMM",
      "IGI2_WAV",
      "iNes",
      "InspectorDates",
      "InspectorWithMP4DateTime",
      "ISO",
      "Java",
      "JavaScript",
      "JPG",
      "KryoFlux",
      "LNK",
      "Luac",
      "LuaJIT",
      "LUKS",
      "LZ4",
      "MachO",
      "MFT",
      "MIDI",
      "Mifare1k",
      "Mifare4k",
      "MifareUltralight",
      "MOBI",
      "Modo",
      "MongoDBWireProtocol",
      "MP3",
      "MP4",
      "MXF",
      "NDS",
      "NetflowVersion5",
      "NTAG215",
      "Nus3Audio",
      "OGG",
      "OPCache",
      "OpenType",
      "OrCAD_LIB",
      "OrCAD_SCH",
      "OscarItem",
      "PAL",
      "PCAP",
      "PCAPNG",
      "PCX",
      "PDF",
      "PHP",
      "Picolog_PLW",
      "PNG",
      "PowerShell",
      "PSF",
      "PYC",
      "Python",
      "Quake3Arena_BSP",
      "Quake3Arena_MD3",
      "RAR",
      "RDB",
      "RegistryDhcpInterfaceOptions",
      "RegistryHive",
      "RegistryPolicyFile",
      "RES",
      "RIFF",
      "RM",
      "ROMFS",
      "SCP",
      "SeqBox",
      "SF2",
      "SHP",
      "ShpcAnim",
      "SHX",
      "SinclairMicrodrive",
      "SQL",
      "SquashFS",
      "SRec",
      "SSP",
      "STL",
      "SWF",
      "SytosPlus",
      "Tacx",
      "TGA",
      "ThumbCache",
      "TIF",
      "TNEF",
      "TOC",
      "Torrent",
      "TTF",
      "ULP",
      "UTMP",
      "VB",
      "VHD",
      "WASM",
      "WAVAdv",
      "WAV",
      "WinhexPos",
      "WMF",
      "XML",
      "ZIPAdv",
      "ZIP",
    ],
    name => {
      test(`reads ${name} definition`, () => {
        const definitionBuffer = fs.readFileSync(`${structureFolder}/${name}.bt`, "UTF-8");
        const definition = importer.readInput(definitionBuffer);

        expect(definition).toBeDefined();
      });
    }
  );
});
